org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=26.1.2
minecraft_version_range=[26.1, )
neo_version=26.1.2.36-beta
neo_version_range=[26,)
mod_id=ultramarine
mod_name=Ultramarine
mod_version=0.8-snapshot
mod_base_package=org.voxelutopia.ultramarine
mod_description=A Chinese Style Minecraft Mod
mod_credits=See credits file
mod_icon=ultramarine_logo.png
mod_authors=Soul_Shadow, LocusAzzurro
mod_group_id=com.voxelutopia.ultramarine

jei_version:29.5.0.28
jade_version_id=7938398