@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.voxelutopia.ultramarine.world.block;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;