@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.voxelutopia.ultramarine.world.block;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;